platform :ios, '9.0'
target 'YWeiBoDemo' do

pod 'MJRefresh', '~> 3.1.0'
#pod 'SDWebImage', '~> 4.4.0'
#pod 'SDWebImage/WebP'
pod 'IQKeyboardManager', '~> 6.2.0'
pod 'CocoaLumberjack', '~> 3.4.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'RealReachability', '~> 1.3.0'
pod 'YYKit', '~> 1.0.0'


end
